# NumPy Arrays

In [1]:
my_list = [1,2,3]


In [2]:
import numpy as np


In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((4))

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5,5)

array([[0.72683886, 0.32411477, 0.92503098, 0.82954047, 0.57566545],
       [0.14740607, 0.4393687 , 0.08842884, 0.11220076, 0.90057936],
       [0.95307351, 0.55843882, 0.49183062, 0.88160874, 0.26285067],
       [0.01335955, 0.34534299, 0.56350996, 0.48027042, 0.0911683 ],
       [0.92338169, 0.74004176, 0.73233708, 0.41808687, 0.97545265]])

In [24]:
np.random.rand(5)

array([0.03441771, 0.45676061, 0.43704057, 0.88039862, 0.53252401])

In [29]:
np.random.randn(4,4)

array([[ 0.20535867, -1.65302924,  0.51579287, -1.73755646],
       [ 0.61842796,  0.32919524,  0.50507001,  1.10214862],
       [-0.38557867, -0.13634434, -0.73483861,  1.12939197],
       [-0.2429864 ,  1.67358466,  0.97912729,  0.23230935]])

In [35]:
np.random.randint(1,100)

2

In [34]:
np.random.randint(1,100,10)

array([51,  8, 25,  9, 85, 18, 58,  5, 12, 14])

In [36]:
ar = np.arange(25)

In [37]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranar = np.random.randint(0,50,10)

In [41]:
ranar

array([32, 13, 30, 15, 23, 22, 19, 14, 17, 43])

In [44]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
ranar.max()

43

In [46]:
ranar.min()

13

In [47]:
ranar.argmax()

9

In [48]:
ranar.argmin()

1

In [50]:
ar.shape

(25,)

In [51]:
arr = ar.reshape(5,5)

In [52]:
arr.shape

(5, 5)

In [53]:
arr.dtype

dtype('int32')

In [54]:
from numpy.random import randint

In [55]:
randint(2,10)

6

In [56]:
arra = np.arange(0,11)

In [57]:
arra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
mike = np.arange(0,10)

In [59]:
mike

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
linda = mike.copy()

In [62]:
linda[0:6] = 44

In [63]:
linda

array([44, 44, 44, 44, 44, 44,  6,  7,  8,  9])

In [64]:
mike

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# # NumPy Indexing and Selection

In [3]:
import numpy as np

In [4]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [5]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
arr_2d[0][0]

5

In [7]:
arr_2d[1,2]

30

In [8]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [9]:
arr_2d[1:,0:]

array([[20, 25, 30],
       [35, 40, 45]])

In [10]:
arr_2d[2:,:1][0][0]

35

In [11]:
arr_2d[2,0]

35

In [12]:
array = np.arange(1,11)

In [13]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
bool_array = array > 5

In [15]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [17]:
array[bool_array]

array([ 6,  7,  8,  9, 10])

In [18]:
array[array>5]

array([ 6,  7,  8,  9, 10])

In [19]:
arr_2d = np.arange(50).reshape(5,10)

In [20]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [21]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# NumPy Operation

In [22]:
import numpy as np

In [23]:
arr = np.arange(0,11)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [31]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
arr +8

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [33]:
arr - 7

array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3])

In [34]:
arr ** 4

array([    0,     1,    16,    81,   256,   625,  1296,  2401,  4096,
        6561, 10000], dtype=int32)

In [35]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [36]:
np.max(arr)

10

In [37]:
np.min(arr)

0

In [38]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [39]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [40]:
np.log(arr)

C:\Users\mike\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])